# Generated by Django 3.0.5 on 2020-09-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['-criado'], 'verbose_name': 'Lista', 'verbose_name_plural': 'Listas'},
        ),
    ]
