# Generated by Django 3.0.5 on 2020-09-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_lista_detalhes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='detalhes',
        ),
    ]
